### ISSUE TITLE
blockcreator with ethvalidation and unencrypted wallet is not creating blocks

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#309]

**Comment by GlenDC** [comment]
The `unencrypted` part is irrelevant here though, that I am sure of.

If it is only when running the `ethvalidation` it might be because it never gets out of this initial sync mode, for some reason, or never starts syncing. If it did sync and your node did get fully started, it should be OK. If not, I would suggest to run in debug mode, to ensure it didn't get trapped somewhere in a panic.

**Comment by robvanmieghem** [comment]
it does seem to be creating blocks now at a normal rate , must have been bad luck initially

**Comment by GlenDC** [comment]
Hmmmm, bad luck in a logic-based system seems suspicious.

**Comment by robvanmieghem** [comment]
will double check

**Comment by robvanmieghem** [comment]
related issue: https://github.com/threefoldtech/rivine/issues/39

**Comment by robvanmieghem** [comment]
Seems fine after all:
```
019/03/01 14:19:38.395190 proofofblockstake.go:39: [DEBUG] [BC] Attempting to solve blocks
2019/03/01 14:19:46.546772 proofofblockstake.go:39: [DEBUG] [BC] Attempting to solve blocks
2019/03/01 14:19:54.701573 proofofblockstake.go:39: [DEBUG] [BC] Attempting to solve blocks
2019/03/01 14:20:02.853224 proofofblockstake.go:39: [DEBUG] [BC] Attempting to solve blocks
2019/03/01 14:20:11.001665 proofofblockstake.go:39: [DEBUG] [BC] Attempting to solve blocks
2019/03/01 14:20:19.155892 proofofblockstake.go:39: [DEBUG] [BC] Attempting to solve blocks
```
as my previous comment 
>it does seem to be creating blocks now at a normal rate , must have been bad luck initially
I guess the hour I was looking at was bad luck
