### ISSUE TITLE
Zero Nodes Offline 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tfchain#310]
A number of zero nodes have been going offline without the hoster turning them off (have talked to them on the phone about this). Please investigate. 
Some examples:
1. Andy Gysbrechts: online now after rebooting again. 
00e04c6805b3 - HYSZ170000803
2. Thomas von Hake 
00e04c6805e7 - HYSZ170000780
3. Bart Buimer
00e04c680a3d - HYSZ170000841
4. Lieve Vereycken
00e04c680a3e - HYSZ170000827

**Comment by sabrinasadik** [comment]
@LeeSmet when could you investigate this?

**Comment by LeeSmet** [comment]
As far as I can see, nodes 1 and 4 in the list above are running, while the other 2 are down. For the nodes which are down, I'd like to know if they are still powered on, and if so, if its possible to connect a keyboard and try to toggle the numlock key (to see if the numlock light turns on/off). If this does not work, that would indicate the node is somehow frozen (likely a bad psu which causes the cpu to lock). If the node is powered down completely, then there is little we can do as it might be caused by a power outage or similar problem.

**Comment by GlenDC** [comment]
Closed for inactivity. Also pretty sure this is out of scope for this project.
