### ISSUE TITLE
Expose graphs to have a visual representation of the chain health

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#72]
https://github.com/rivine/rivine/issues/288

**Comment by GlenDC** [comment]
I like it, even though I really think this should be a separate service, which collects for multiple sources, as to help in ensuring the numbers are correct. Now one would have to check and manually compare different graphs to be really sure. Normally all explorers should give the same result though, but we all know that due to some reasons they might differ.

**Comment by robvanmieghem** [comment]
@GlenDC blocks and the info do not differ per node, one can be out of sync and be behind a bit but that's it.

**Comment by LeeSmet** [comment]
For now some basic graphs, can always be updated later should the need arise
